repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: ["--fix", "--config=pyproject.toml"]
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: ["--line-length=88"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: ["types-PyYAML"]
        args: ["--config-file=pyproject.toml"]
        files: ^src/crypto_bot/
  - repo: local
    hooks:
      - id: pytest
        name: pytest (pre-push)
        entry: pytest -q
        language: system
        pass_filenames: false
        stages: [pre-push]
