"""add domain_event table for event sourcing

Revision ID: 811f2e9e8b61
Revises: 90f93590835d
Create Date: 2025-10-19 15:39:11.318920

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "811f2e9e8b61"
down_revision: str | Sequence[str] | None = "90f93590835d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain_event",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "event_metadata", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_domain_event_aggregate_id"),
        "domain_event",
        ["aggregate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_domain_event_aggregate_type"),
        "domain_event",
        ["aggregate_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_domain_event_event_type"), "domain_event", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_domain_event_occurred_at"),
        "domain_event",
        ["occurred_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_domain_event_occurred_at"), table_name="domain_event")
    op.drop_index(op.f("ix_domain_event_event_type"), table_name="domain_event")
    op.drop_index(op.f("ix_domain_event_aggregate_type"), table_name="domain_event")
    op.drop_index(op.f("ix_domain_event_aggregate_id"), table_name="domain_event")
    op.drop_table("domain_event")
    # ### end Alembic commands ###
