# Base configuration - inherited by all environments
# Do NOT put sensitive data here - use environment variables

app:
  name: "Crypto Trading Bot"
  version: "0.1.0"
  log_level: "INFO"

database:
  host: "localhost"
  port: 5432
  name: "crypto_bot"
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 1800
  echo: false

redis:
  host: "localhost"
  port: 6379
  db: 0
  socket_timeout: 5
  socket_connect_timeout: 5
  max_connections: 50

trading:
  dry_run: true
  max_concurrent_trades: 5
  default_order_type: "limit"
  risk:
    # Stop Loss Configuration
    stop_loss:
      enabled: true
      percentage: 2.0  # 2% stop loss
      cooldown_seconds: 60
      trailing: false
    
    # Take Profit Configuration
    take_profit:
      enabled: true
      percentage: 5.0  # 5% take profit
      cooldown_seconds: 60
      partial_close: false
      partial_close_percentage: null
    
    # Exposure Limits Configuration
    exposure_limit:
      max_per_asset: 10000.0  # Max $10k per asset
      max_per_exchange: 30000.0  # Max $30k per exchange
      max_total: 50000.0  # Max $50k total exposure
      base_currency: "USDT"
    
    # Trailing Stop Configuration
    trailing_stop:
      enabled: true
      trailing_percentage: 3.0  # Trail 3% below peak
      activation_percentage: 5.0  # Activate after 5% profit
      update_interval_seconds: 5
    
    # Max Concurrent Trades Configuration
    max_concurrent_trades:
      max_trades: 5  # Maximum 5 concurrent trades
      max_per_asset: 1  # Only 1 position per asset
      max_per_exchange: 3  # Max 3 trades per exchange
    
    # Drawdown Control Configuration
    drawdown_control:
      max_drawdown_percentage: 15.0  # Max 15% drawdown
      enable_emergency_exit: true
      emergency_exit_percentage: 20.0  # Emergency exit at 20%
      pause_trading_on_breach: true
      calculation_period_days: 30
    
    # Risk Check Settings
    risk_check_interval: 1.0  # Check every second
    emergency_only_mode: false
  
  execution:
    order_timeout_seconds: 30
    retry_attempts: 3
    retry_delay_seconds: 2

strategies:
  enabled: []
  default_params: {}

exchanges:
  binance:
    enabled: false
    sandbox: true
    rate_limits:
      requests_per_second: 10
      orders_per_day: 200000
  coinbase:
    enabled: false
    sandbox: true
    rate_limits:
      requests_per_second: 3
      orders_per_day: 10000

api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  reload: false
  cors:
    enabled: true
    origins: ["http://localhost:3000"]

logging:
  level: "INFO"
  file_path: "./data/logs/crypto-bot.log"
  max_size: "10MB"
  backup_count: 5
  format: "json"
  handlers:
    - console
    - file

monitoring:
  enabled: true
  metrics_enabled: true
  health_check_interval: 60

notifications:
  telegram:
    enabled: false
  discord:
    enabled: false
  email:
    enabled: false

