# Base configuration - inherited by all environments
# Do NOT put sensitive data here - use environment variables

app:
  name: "Crypto Trading Bot"
  version: "0.1.0"
  log_level: "INFO"

database:
  host: "localhost"
  port: 5432
  name: "crypto_bot"
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 1800
  echo: false

redis:
  host: "localhost"
  port: 6379
  db: 0
  socket_timeout: 5
  socket_connect_timeout: 5
  max_connections: 50

trading:
  dry_run: true
  max_concurrent_trades: 5
  default_order_type: "limit"
  risk:
    max_position_size_pct: 10.0
    max_portfolio_risk_pct: 30.0
    default_stop_loss_pct: 2.0
    default_take_profit_pct: 5.0
    max_drawdown_pct: 15.0
  execution:
    order_timeout_seconds: 30
    retry_attempts: 3
    retry_delay_seconds: 2

strategies:
  enabled: []
  default_params: {}

exchanges:
  binance:
    enabled: false
    sandbox: true
    rate_limits:
      requests_per_second: 10
      orders_per_day: 200000
  coinbase:
    enabled: false
    sandbox: true
    rate_limits:
      requests_per_second: 3
      orders_per_day: 10000

api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  reload: false
  cors:
    enabled: true
    origins: ["http://localhost:3000"]

logging:
  file_path: "./data/logs/crypto-bot.log"
  max_size: "10MB"
  backup_count: 5
  format: "json"
  handlers:
    - console
    - file

monitoring:
  enabled: true
  metrics_enabled: true
  health_check_interval: 60

notifications:
  telegram:
    enabled: false
  discord:
    enabled: false
  email:
    enabled: false

